### ISSUE TITLE
OpenAPI/Swagger spec

### ISSUE THREAD

**Issue by HavenDV** [tryAGI/AI21#1]
https://github.com/AI21Labs/studio-demos/issues/3

**Comment by uripeled2** [comment]
Where can I find the OpenAPI/Swagger spec you generated to create this SDK?

**Comment by HavenDV** [comment]
As I remember, I found this while trying to add openapi.yaml/openapi.json to their documentation and it worked. Here's the url: https://api.ai21.com/openapi.json
